### ISSUE TITLE
Xamarin.GooglePlayServices compile error in Mac

### ISSUE THREAD

**Issue by windsql** [xamarin/GooglePlayServicesComponents#53] opened 2017-03-22 04:09 UTC
### Xamarin.Android Version (eg: 6.0):
xamarin.android-7.1.0-43

### Operating System & Version (eg: Mac OSX 10.11):
Mac OSX 10.11

### Google Play Services Version (eg: 8.4.0):
Xamarin.GooglePlayServices.Maps.42.1001.0
Xamarin.GooglePlayServices.Tasks.42.1001.0
Xamarin.GooglePlayServices.Basement.42.1001.0
Xamarin.GooglePlayServices.Base.42.1001.0

### Describe your Issue:
__AndroidLibraryProjects__.zip unzip error
![image](https://cloud.githubusercontent.com/assets/4011797/24181612/f9baf5d0-0ef6-11e7-9938-b4f4ad2f1a0e.png)
It should unzip like this 
![image](https://cloud.githubusercontent.com/assets/4011797/24181644/3f39f610-0ef7-11e7-88ef-b53e89557f7f.png)

### Steps to Reproduce (with link to sample solution if possible):
Build it on Mac use the Xamarin.GooglePlayServices.Maps.42.1001.0 Version

**Comment by Redth** [comment] 2017-04-04 13:14
I'm not seeing anything obviously wrong.

Could you post some more information?  Stack traces? Diagnostic build logs?  Reproducible Sample solution?  Any or all of those would help.

**Comment by windsql** [comment] 2017-04-06 09:04
Could you just setup a new solution and build the android project in Mac with Xamarin Studio,then you'll find the problem.

**Comment by Redth** [comment] 2017-04-07 13:28
I just made a new project in Xamarin Studio on Mac and added those nuget packages, it all compiles fine...  I'm really confused as to how you're getting this result.

Can you attach a reproducible solution?

**Comment by Redth** [comment] 2017-04-18 14:10
I'm closing this as a duplicate of https://github.com/xamarin/AndroidSupportComponents/issues/45 because whatever the issue is, it will be the same in Android Support Libraries (it's likely more to do with Xamarin.Build.Download than anything else).  Also, Android Support Libraries will be a simpler case to repro this against.

**Closed by Redth** 2017-04-18 14:10 UTC
Labels: duplicate
