### ISSUE TITLE
Issues with Xamarin.GooglePlayServices.Ads.Lite 71.1.17.2.0 cannot compile

### ISSUE THREAD

**Issue by FANMixco** [xamarin/GooglePlayServicesComponents#240] opened 2019-07-28 15:55 UTC
### Xamarin.Android Version (eg: 6.0):

> Xamarin.Android
> Version: 9.4.0.51 (Visual Studio Community)
> Commit: xamarin-android/d16-2/9fa7775
> Android SDK: /Users/fanmixco/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		8.1 (API level 27)

### Operating System & Version (eg: Mac OSX 10.11):

> Mac OS X 10.14.5
> Darwin 18.6.0 Darwin Kernel Version 18.6.0
>     Thu Apr 25 23:16:27 PDT 2019
>     root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

### Google Play Services Version (eg: 8.4.0):
71.1.17.2.0

### Describe your Issue:
Cannot compile. I just added the library and I got this issue:

<img width="1264" alt="Screen Shot 2019-07-28 at 17 54 13" src="https://user-images.githubusercontent.com/1666156/62009543-bef1b880-b160-11e9-81a4-a92b4624ae11.png">

### Steps to Reproduce (with link to sample solution if possible):

Just add the library to any of these projects:

https://github.com/xamarin/xamarin-android/issues/3263#issuecomment-514046705

And clean and build.

### Include any relevant Exception Stack traces, build logs, adb logs:

```
/Users/fanmixco/Documents/GitHub/lrm-android/TheMayanRoute/obj/Debug/android/src/mono/com/google/android/gms/ads/reward/mediation/MediationRewardedVideoAdListenerImplementor.java(8,8): Error:  error: MediationRewardedVideoAdListenerImplementor is not abstract and does not override abstract method zzc(Bundle) in MediationRewardedVideoAdListener
public class MediationRewardedVideoAdListenerImplementor
 (TheMayanRoute)
```

**Comment by moljac** [comment] 2019-07-29 08:14
Duplicate of
https://github.com/xamarin/GooglePlayServicesComponents/issues/236

Fix for this issue is in 71.20190729.

Closing - duplicate

**Closed by moljac** 2019-07-29 08:14 UTC
