### ISSUE TITLE
FirebaseOptions.getProjectId() cannot be null.

### ISSUE THREAD

**Issue by darkdoctor** [xamarin/GooglePlayServicesComponents#162] opened 2018-11-18 13:02 UTC
Greetings.

I just read "https://github.com/xamarin/GooglePlayServicesComponents/issues/104" and can anyone please update me if this is fixed.

I still get FirebaseOptions.getProjectId() cannot be null.

Google analytics works pretty fine. I have google-services.json included on my project and set build action as google services.

**Comment by schrizzity** [comment] 2018-11-18 22:30
Look at this comment for a work around. This worked for me...

[https://github.com/xamarin/GooglePlayServicesComponents/issues/104#issuecomment-406681123](url)

**Comment by Redth** [comment] 2018-11-20 02:49
Duplicate of #104

**Closed by Redth** 2018-11-20 02:49 UTC
