### ISSUE TITLE
Aztec decoder

### ISSUE THREAD

**Issue by tomcio1205** [xamarin/GooglePlayServicesComponents#244] opened 2019-08-04 21:50 UTC
### Xamarin.Android Version (eg: 6.0):
9.0

### Operating System & Version (eg: Mac OSX 10.11):
Mac OSX 10.14.5

### Google Play Services Version (eg: 8.4.0):

71.1702
### Describe your Issue:
It is possible to scan Aztec qrcodes? I didn't see Aztec option in BarcodeFormat enum :(

**Comment by moljac** [comment] 2019-08-05 07:05
@tomcio1205 
Does Google java APIs support it? Can you provide more info? Which atifact/nuget?

**Comment by tomcio1205** [comment] 2019-08-05 08:09
As I can see in the doc APIs supports it. 
[https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/BarcodeDetector.Builder](url)
In nuget Xamarin.GooglePlayServices.Vision (ver. 1.0.0.0), i see all types which are described in doc except AZTEC, and ALL_FORMATS. This types are in the Android.Gms.Vision.Barcodes namespace, as BarcodeFormat enum.

**Comment by genifycom** [comment] 2019-09-20 20:00
How far away is this fix? I need Aztec

**Comment by moljac** [comment] 2019-10-03 12:12
Fixed in 71.20190930.

Xamarin.GooglePlayServices.Vision 71.1702.1

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Vision/71.1702.1

Please let me know if the issue is fixed

**Comment by yma44** [comment] 2019-10-03 22:07
Great! I can scan aztec barcode with 71.1.702.1.   Thanks!!

**Comment by genifycom** [comment] 2019-10-04 22:56
Confirmed Aztec. Thank you

**Comment by genifycom** [comment] 2019-10-04 23:23
MobileManager -> Xamarin.GooglePlayServices.Vision 71.1702.1 -> Xamarin.GooglePlayServices.Basement 71.1620.0 -> Xamarin.Android.Support.v4 28.0.0.1 -> Xamarin.Android.Support.Compat (= 28.0.0.1).
Package restore failed. Rolling back package changes for 'MobileManager'.

On a new project, Xamarin.GooglePlayServices.Vision will not install immediately as Xamarin.Android.Support.Compat is 28.0.0.3

**Comment by moljac** [comment] 2019-10-05 12:01
@genifycom Please open new issue. This is something different and darn dependency chains with exact versions are killing us/me. We are aware of that problem.

Thanks everybody for feedback.

Closing this one!

**Closed by moljac** 2019-10-05 12:01 UTC
