### ISSUE TITLE
Xamarin GooglePlayServices Binding update

### ISSUE THREAD

**Issue by ivocarminati** [xamarin/GooglePlayServicesComponents#116] opened 2018-06-01 13:24 UTC
Hi all,

I'm using your latest binding for Xamarin GooglePlayServices (v. 11.4.2), but there are some related bugs that Google has resolved with the latest version of GooglePlayService 15.0.0.
I would like to know if some newer version of bindings is going to be released soon because I need urgent solutions for solve issues in my project. 
Have you planned some release? 

Thanks in advance,
Ivo

**Comment by csdinon** [comment] 2018-06-01 17:35
@ivocarminati duplicate of #112

**Comment by csdinon** [comment] 2018-06-01 17:36
#112

**Comment by Redth** [comment] 2018-07-23 14:34
Working on these, thanks.

**Closed by Redth** 2018-07-23 14:34 UTC
Labels: duplicate
