### ISSUE TITLE
Cannot find PlacePicker in Android.Gms.Location.Places.UI

### ISSUE THREAD

**Issue by muhaym** [xamarin/GooglePlayServicesComponents#33] opened 2016-10-31 07:40 UTC
### Xamarin.Android Version (eg: 6.0)
7.0

### Operating System & Version (eg: Mac OSX 10.11)
Mac OS 10.12.1

### Google Play Services Version (eg: 8.4.0)
Nuget 32.940.0 beta 3 

### Describe your Issue
Can't find PlacePicker class as per the https://developers.google.com/android/reference/com/google/android/gms/location/places/ui/package-summary
in Android.Gms.Location.Places.UI

Installed GMS.Location, GMS.Maps, GMS.Places and the all other dependent nugets
<img width="1217" alt="screen shot 2016-10-31 at 12 58 13 pm" src="https://cloud.githubusercontent.com/assets/10905479/19847168/efd77ba2-9f6a-11e6-910f-890f99b61907.png">

**Comment by Redth** [comment] 2016-12-05 17:29
Thanks, this is fixed in the released stable version 32.961.0 nuget.

**Closed by Redth** 2016-12-05 17:29 UTC

**Comment by SharpMobileCode** [comment] 2017-05-07 16:52
@Redth  Just an update, there's a possible regression, I updated to v42.102.1.0 and `Android.Gms.Location.Places.UI.PlacePicker` has disappeared.

**Comment by SharpMobileCode** [comment] 2017-05-07 16:54
Downgraded to 42.1001.0 and PlacePicker is present.

**Comment by Redth** [comment] 2017-05-17 14:03
Try `42.1021.1` it should be back.

**Comment by TravisFleenor** [comment] 2018-07-02 12:37
I'm currently trying to use 42.1021.1 because a nuget package I want to use depends on it. It's missing in that version. Anyone have a workaround for this that doesn't involve updating?
