### ISSUE TITLE
awarnesss api not works awarness api client is not connect

### ISSUE THREAD

**Issue by halukmy** [xamarin/GooglePlayServicesComponents#55] opened 2017-04-04 14:14 UTC
### Xamarin.Android Version (eg: 6.0):
7.1

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Describe your Issue:
awarness api client is not connect

**Comment by Redth** [comment] 2017-04-04 18:40
Duplicate of #51

**Closed by Redth** 2017-04-04 18:40 UTC
