### ISSUE TITLE
Xamarin.Firebase.Perf build error

### ISSUE THREAD

**Issue by PavloLukianets** [xamarin/GooglePlayServicesComponents#898] opened 2024-08-01 08:49 UTC
### Xamarin.Android Version (eg: 6.0):
Latest net8.0 android

### Operating System & Version (eg: Mac OSX 10.11):
MacOS Sonoma Version 14.5 (23F79)

### Google Play Services Version
Latest nugets available

### Describe your Issue
Installing **Xamarin.Firebase.Perf** in a blank template Android app produces build error. Tips and workarounds in https://github.com/xamarin/AndroidX/issues/764 don't help

### Repro
[AndroidApp1.zip](https://github.com/user-attachments/files/16452739/AndroidApp1.zip)

### Include any relevant Exception Stack traces, build logs, adb logs:
```
0>: Error JAVA0000 java: Error in obj/Debug/net8.0-android/lp/173/jl/classes.jar:com/google/protobuf/DescriptorProtos$1.class:
Type com.google.protobuf.DescriptorProtos$1 is defined multiple times: obj/Debug/net8.0-android/lp/173/jl/classes.jar:com/google/protobuf/DescriptorProtos$1.class, obj/Debug/net8.0-android/lp/162/jl/libs/8E428AF64A795598.jar:com/google/protobuf/DescriptorProtos$1.class
...
Directory 'obj/Debug/net8.0-android/lp/151' is from 'protolite-well-known-types.aar'.
```

**Comment by PavloLukianets** [comment] 2024-08-01 09:40
I see that a fix was already implemented over here, however looks like the issue is still not resolved : https://github.com/xamarin/GooglePlayServicesComponents/commit/d4fd4c08a5abf6459b4171cd5be5c4ff9cb1a0db

**Comment by Digifais** [comment] 2024-08-13 08:35
I can confirm this is an issue with `Xamarin.FIrebase.Perf 121.0.1.1`, latest working version on my end seems to be `121.0.0`.

**Comment by Digifais** [comment] 2024-08-13 09:06
@PavloLukianets Yes, it does for me.

**Comment by PavloLukianets** [comment] 2024-08-15 09:13
Nope, for my combination of libs doesn't build. So, waiting for fix from the team

**Comment by PavloLukianets** [comment] 2024-08-21 16:24
https://github.com/firebase/firebase-android-sdk/pull/5999

**Comment by Digifais** [comment] 2024-08-21 17:34
> [firebase/firebase-android-sdk#5999](https://github.com/firebase/firebase-android-sdk/pull/5999)

@moljac

**Comment by moljac** [comment] 2024-08-22 05:51
@Digifais 

Thanks for the info. We added fix on our side, but I expect more to come. Google's ecosystem is one huge construction site (kotlin multiplatform).

> > [firebase/firebase-android-sdk#5999](https://github.com/firebase/firebase-android-sdk/pull/5999)
> 
> @moljac

**Comment by moljac** [comment] 2024-10-01 17:59
closing this issue

**Closed by moljac** 2024-10-01 17:59 UTC
