### ISSUE TITLE
Missing xml docs in assemblies

### ISSUE THREAD

**Issue by rsheptolut** [xamarin/GooglePlayServicesComponents#346] opened 2020-05-25 12:40 UTC
### Xamarin.Android Version (eg: 6.0):
8.1

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Google Play Services Version

*   [] GPS-FB with Android.Support (legacy) dependencies (versions `71.yyyy.zz`)
Xamarin.GooglePlayServices.Maps 60.1142.1

### Describe your Issue
Thanks for the awesome work! My problem is - I'm not seeing any XML docs in Visual Studio for this package. Meaning, no intellisense documentation for classes, methods and properties in Xamarin.GooglePlayServices.Maps (haven't worked with other GPS packages yet). Is this by design? I'm very used to always having that for all packages, it's very valuable to have those and not have to google every little thing. F1 also doesn't work, but that never works for any real stuff. In Android Studio you can apparently manually invoke the javadoc for these same APIs (classes, methods and properties for Google Maps) by clicking Ctrl+Q. Is there something like this in Visual Studio and I'm missing it? Is this resolved in 1xx.yyyy.zz? I thought I was using the newest sample for using Google maps in your Xamarin Android app. Thanks again!

### Relevant information

Packages used:

```
<PackageReference Include="Xamarin.GooglePlayServices.Maps"><Version>60.1142.1</Version></PackageReference>
<PackageReference Include="Xamarin.Android.Support.Design"><Version>27.0.2.1</Version></PackageReference>
```

**Comment by moljac** [comment] 2020-05-27 14:59
> Thanks for the awesome work! 

Thanks. You are welcome, but we must thank you too - feedback means a lot to us.

> My problem is - I'm not seeing any XML docs in Visual Studio for this package. Meaning, no intellisense documentation for classes, methods and properties in Xamarin.GooglePlayServices.Maps (haven't worked with other GPS packages yet). 

Nope. It is not by design and not only your problem. You should see what we do to be more productive with bindings - combining VS Code and VS4Mac/VS4w2019

Out tools do not emit XML docs in generated code. But for that we must dig deeper to explain it to you.

> Is this by design? 

Nope. Sorry.

> I'm very used to always having that for all packages,

We are all a bit spoiled with nice stuff in .NET ecosystem (VS4W)

> it's very valuable to have those and not have to google every little thing. F1 also doesn't work, but that never works for any real stuff. In Android Studio you can apparently manually invoke the javadoc for these same APIs (classes, methods and properties for Google Maps) by clicking Ctrl+Q. Is there something like this in Visual Studio and I'm missing it? 

No. Not yet, but we are working on it. 1st to catch up with google's cadence and then to add sugar coating.

> Is this resolved in 1xx.yyyy.zz? 

No.

71.xxx are GPS-FB (Google Play Services and Firebase)with Android.Support dependencies
and
100.xxx are GPS-FB with AndroidX dependencies

No productivity enhancements (xml docs, etc), jut bindings of newer artifacts.

> I thought I was using the newest sample for using Google maps in your Xamarin Android app.

I think I saw branch with Xamarin.Forms.Maps which use 1xx.yyy (AndroidX) Google Maps which are [still] in peview. (I want to fix few more smaller samples). That might be a good starting point.

> Thanks again!

Thank You.

Due to the fact that there will be no XML doc support soon, I would appreciate if this answer is something satisfying - I would appreciate closing this issue.

**Closed** 2021-05-24 23:02 UTC
Labels: investigating, not-an-issue, not-on-roadmap
