### ISSUE TITLE
Firebase SDK has not been updated

### ISSUE THREAD

**Issue by horaciojcfilho** [xamarin/GooglePlayServicesComponents#185] opened 2019-02-27 02:54 UTC
For 7 months, there is no more updates to the Firebase packages in Nuget. Please, may the Components team get the Firebase packages a more cycle of updates? Many thanks in advance.

**Comment by michaelwanke** [comment] 2019-02-27 17:03
#163 has some more detail if helpful.

**Comment by Redth** [comment] 2019-03-01 02:20
We are working on these and are very close!

Closing as Duplicate of #163

**Closed by Redth** 2019-03-01 02:20 UTC
