### ISSUE TITLE
[70.1620.0-preview2] Xamarin.Firebase.Iid.FirebaseInstanceId.Instance returns null

### ISSUE THREAD

**Issue by jahmai** [xamarin/GooglePlayServicesComponents#134] opened 2018-08-10 05:00 UTC
### Xamarin.Android Version (eg: 6.0):

8.3.3.2

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10

### Google Play Services Version (eg: 8.4.0):

70.1620.0-preview2

### Describe your Issue:

Xamarin.Firebase.Iid.FirebaseInstanceId.Instance returns null

### Steps to Reproduce (with link to sample solution if possible):

Add reference to Xamarin.Firebase.Iid 70.1620.0-preview2 nuget package.
Access Xamarin.Firebase.Iid.FirebaseInstanceId.Instance
It appears from looking at the type that none of the members are available / are null.

### Include any relevant Exception Stack traces, build logs, adb logs:

**Comment by jahmai** [comment] 2018-08-10 10:31
I noticed that Firebase.Iid manifest wasn't getting merged, like issue #114. However I've manually added the manifest below into my apps main manifest and it didn't help:

```
		<receiver
				android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
				android:exported="true"
				android:permission="com.google.android.c2dm.permission.SEND" >
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<category android:name="${applicationId}" />
			</intent-filter>
		</receiver>
		<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
			<meta-data
					android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
					android:value="com.google.firebase.components.ComponentRegistrar" />
		</service>
```

**Comment by jahmai** [comment] 2018-08-11 09:08
Also, FirebaseMessageService.OnNewToken isn't getting called, even on app reinstall. I suspect the issues are linked.

**Comment by Natoito** [comment] 2018-08-16 10:04
Hi, I wanted to create topic about this problem but I found this one. Xamarin.Firebase.Iid.FirebaseInstanceId.Instance returns null and FirebaseMessageService.OnNewToken is not called like @jahmai mentioned.

**Xamarin.Forms Version**
3.2.0.729530-pre2

**Xamarin.Firebase.Messaging Version**
70.1710.0-preview2

**Xamarin.GooglePlayServices.Base  Version**
70.1501.0-preview2

**Comment by Natoito** [comment] 2018-08-16 10:49
I just received Visual Studio update to 15.8.0 version and now everything is working. OnNewToken is now called and FirebaseInstanceId.Instance is initialized.

**Comment by newky2k** [comment] 2018-08-20 20:52
seems to be fixed via the latest update to Visual Studio and Xamarin.Android

**Closed by newky2k** 2018-08-20 20:52 UTC

**Comment by hadigityat** [comment] 2019-03-21 22:51
I'm still having this issue on: 

=== Visual Studio Community 2017 for Mac ===

Version 7.8.3 (build 2)
Installation UUID: e54e9990-6782-4238-a6cd-797dff2cf7f1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516010000

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.1.0 (2018-06/a76b50e5faa) (64-bit)
	Package version: 516010000

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.16 (Visual Studio Community)
Hash: 2dc06c71
Branch: 
Build date: 2019-02-12 23:09:50-0500

=== Xamarin.Android ===

Version: 9.1.8.0 (Visual Studio Community)
Android SDK: /Users/Can/Downloads/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/Can/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.8.1.0
Hash: 8924ea4a

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 12.2.1.15 (Visual Studio Community)
Hash: d60abd198
Branch: d15-9
Build date: 2019-02-01 12:23:29-0500

=== Build Information ===

Release ID: 708030002
Git revision: fd02e670fdd6b101bc9c08b1cc5b7710d9f58cd8
Build date: 2019-03-08 10:30:21+00
Build branch: release-7.8
Xamarin extensions: 1f72f0a3737128552336f27e189d3c4f0cdebd00

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64


Crash Log:
Error (24512) / AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
Error (24512) / AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
Error (24512) / AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
Error (24512) / AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
Error (24512) / AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
Error (24512) / AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
Error (24512) / AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
Error (24512) / AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
Error (24512) / AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.getInstanceId()' on a null object reference
Error (24512) / AndroidRuntime: 	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
Error (24512) / AndroidRuntime: 	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
Error (24512) / AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
Error (24512) / AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error (24512) / AndroidRuntime: 	... 3 more
