### ISSUE TITLE
Firebase Crashlytics for Xamarin.Forms.

### ISSUE THREAD

**Issue by vivekshah-zymr** [xamarin/GooglePlayServicesComponents#123] opened 2018-07-06 07:33 UTC
I am developing an app in xamarin forms for Android and iOS. In which I want to track the crash, So Can anyone help me, how can I integrate Firebase Crashlytics for Android and iOS both.
I found [NuGet package for iOS ](https://www.nuget.org/packages/Xamarin.Firebase.iOS.Crashlytics/), but not able to use that. So Please help me with this.

**Comment by Redth** [comment] 2018-07-23 14:30
We're working on bindings for the Android version.  In the meantime, there's other options available like AppCenter.ms for crash reporting.

Duplicate of #93

**Closed by Redth** 2018-07-23 14:30 UTC
Labels: duplicate

**Comment by jrahma** [comment] 2018-08-03 08:39
it will be great if Crashlytics will be available for Xamarin Forms too.

**Comment by me-Henok** [comment] 2019-10-28 06:39
I need to use firebase crashlytics in my xamarin forms app any detailed documentation on how to set up  in XF
