### ISSUE TITLE
 Firebase.Firestore.FieldValue does not contain a definition for ArrayUnion

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/GooglePlayServicesComponents#177] opened 2019-02-05 02:36 UTC
_From @sdiaz-qkt on February 4, 2019 16:46_

Hello. I'm currently working with Firestore in iOS and Android using Xamarin. I'm trying to add a value to an existing array in firestore. In iOS I had no problems using FieldValue.FromArrayUnion(obj). However in Android I'm having a hard time since this method does not exist.  I believe this should be consider a bug, specially since I still has no clue on how to add a value to my array in Xamarin.Android. 

_Copied from original issue: xamarin/xamarin-android#2689_

**Comment by moljac** [comment] 2019-04-08 17:21
This will need Firestore version 17.0.5+ and due to complex dependencies it will take some time to resolve those dependencies for Google.Play.Services and Firebase nugets.

In other words - we are working on this issue.

**Comment by moljac** [comment] 2019-06-21 10:29
@sdiaz-qkt @aixiaozi @jonathanpeppers
```
public static unsafe global::Firebase.Firestore.FieldValue ArrayUnion (params global::Java.Lang.Object[] elements)
```

is surfaced for sure in `71.*-preview8` (checked) which will be published soon.  

It may be in `71.*-preview7` which is already published, but I did not check it before publishing.

If the problem is sloved please close this issue (if you can) or report the results here, so I can close it.

**Comment by moljac** [comment] 2019-07-09 14:31
closing this one

**Closed by moljac** 2019-07-09 14:31 UTC
Labels: in-progress
