### ISSUE TITLE
Solution fails to open after build script

### ISSUE THREAD

**Issue by vbisbest** [xamarin/GooglePlayServicesComponents#38] opened 2016-12-01 16:50 UTC
### Xamarin.Android Version (eg: 6.0):
Latest

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10 Visual Studio 2015

### Google Play Services Version (eg: 8.4.0):
NA

### Describe your Issue:
The build script runs fine, no isssues.  However, when I open the solution afterwards, VS just locks up.   You have to kills the VS task to close it.   The only way to open it is to delete the entire project and repull it down again from Github.

**Comment by xtu** [comment] 2016-12-29 00:01
I have the same issue on the same platform. I am opening the ```GooglePlayServicesComponents-master\vision\samples\VisionSample.sln``` and VS locks after I changed the target Android version from 24 to 25.

**Comment by Redth** [comment] 2017-01-26 14:28
Is this still happening on the https://github.com/xamarin/GooglePlayServicesComponents/tree/v10.0.1 branch? I'm unable to reproduce it locally.

**Comment by xtu** [comment] 2017-02-02 22:55
I am not able to load all the project in PlayServices folder after installing Xamarin for Visual Studio v4.2.13, so I can't produce more information at the moment.

**Comment by Redth** [comment] 2017-04-04 12:38
I wonder if this is related to our Xamarin.Build.Download issues.  Please try updating to Xamarin.Build.Download 0.4.3 and try again.  You can do this by pulling and building the `v10.2.1` branch.

**Comment by Redth** [comment] 2017-04-06 20:59
Closing this issue for now, please let us know (or open a new issue) if updating to Xamarin.Build.Download 0.4.3 does not help.

**Closed by Redth** 2017-04-06 20:59 UTC
Labels: need-info
