### ISSUE TITLE
Upgrating package Xamarin.Firebase.Messaging from v119.0.1 to v120.1.7 makes FirebaseMessagingService missing and project to failt to build.

### ISSUE THREAD

**Issue by XDarinor** [xamarin/GooglePlayServicesComponents#353] opened 2020-06-08 23:39 UTC
### Xamarin.Android Version (eg: 6.0):

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

### Operating System & Version (eg: Mac OSX 10.11):

Windows 10 build 10.0.18363.836

### Describe your Issue

Upgrading Xamarin.Firebase.Messaging from package version 119.0.1-preview1 to latest version 120.1.7-preview01 breaks my code. The class FirebaseMessagingService is missing completely. Reverse back to 119.0.1-preview01 brings all back to normal.

### Relevant information
```xml
<PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory">
      <Version>5.2.7</Version>
    </PackageReference>
    <PackageReference Include="NLog">
      <Version>4.7.2</Version>
    </PackageReference>
    <PackageReference Include="NLog.Config">
      <Version>4.7.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.Core.Utils" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.AndroidX.AppCompat">
      <Version>1.1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Browser">
      <Version>1.2.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.CardView">
      <Version>1.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout">
      <Version>1.1.3.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Core">
      <Version>1.2.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.DrawerLayout">
      <Version>1.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Fragment">
      <Version>1.2.4.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.GridLayout">
      <Version>1.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Common">
      <Version>2.2.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Migration">
      <Version>1.0.6.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Transition">
      <Version>1.3.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
    <PackageReference Include="Xamarin.Google.Android.Material">
      <Version>1.1.0.1-rc3</Version>
    </PackageReference>
    <PackageReference Include="Realm">
      <Version>4.3.0</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>12.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v4">
      <Version>28.0.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData">
      <Version>2.2.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.GooglePlayServices.Base">
      <Version>117.2.1-preview01</Version>
    </PackageReference>
```
Actually, to make project build the v119 version of Xamarin.Firebase.Messaging package is needed, as v120.1.7 breaks the solution.

    <PackageReference Include="Xamarin.Firebase.Messaging">
      <Version>119.0.1-preview01</Version>
    </PackageReference>

Tools settings`

    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>

### Steps to Reproduce (with link to sample solution if possible):

Just jump from Xamarin.Firebase.Messaging v119.0.1-preview01 to v120.1.7-preview01

**Comment by moljac** [comment] 2020-06-14 16:52
The issue was caused by new obfuscated class.

Version 120.1.7 fixed in:
 https://github.com/xamarin/GooglePlayServicesComponents/commit/9aff6c77a847f4a9fa3305dc35d06976d1760bef

Version 120.0.1 fixed in:

https://github.com/xamarin/GooglePlayServicesComponents/commit/6f5e4c5f16f0101662bcaf74c6ab1134202cfb88

**Comment by Dona278** [comment] 2020-06-30 21:07
Hi @moljac ! When could we find the 120.1.7 version?
Thanx

**Comment by Dona278** [comment] 2020-07-07 06:36
Hi @moljac, there are news for the updated preview package on nuget with this fix?
Both 120.1.0-preview01 and 120.1.7-preview01 haven't the `FirebaseMessagingService` class and if I use the version 119.0.1-preview03 I get `'Illegal class access: 'com.google.firebase.messaging.zze' attempting to access 'com.google.firebase.iid.zzat' (declaration of 'com.google.firebase.messaging.zze' appears in /data/app/com.loonyhair.android-yqasV4LyZ5MJX8iAcuxa8A==/base.apk)'`.

I also tried to use the version 119.0.1-preview03 and update all its dependencies but the error appears again

**Comment by moljac** [comment] 2020-07-07 07:35
@Dona278 
Yes. There are always some news.

Though I need to fix some issues in AndroidX which cause issues in GPS-FB. i wanted to skip previews and go for the release, but because of pressure I will publish next round of previews.

**Comment by moljac** [comment] 2020-07-07 09:42
@Dona278 

I'm finishing AndroidX updates which were released in 202006 (mid or 1st half).
Then I have 2-3 smaller issues mostly to test. I think I might start releasing previews today or tomorrow. Depends on roadblocks I might hit today.

In general the unit of time should be day, not week. 
Ciao

**Comment by moljac** [comment] 2020-07-17 10:01
published

* 120.1.0-preview02 
* 120.1.7-preview02

https://www.nuget.org/packages/Xamarin.Firebase.Messaging

@Dona278 

Could you provide info if this is OK, please? Or better, close this issue yourself.

Thanks

**Comment by Dona278** [comment] 2020-07-20 05:59
Hi @moljac, all works fine now! But I can't close this issue because isn't opened from me.

Grazie!

**Comment by moljac** [comment] 2020-07-20 08:29
OK. Closing. Thanks @Dona278

**Closed by moljac** 2020-07-20 08:29 UTC
Labels: in-test, solved-waiting-confirmation
