### ISSUE TITLE
[Regression] Xamarin.Firebase.Analytics 121.2.2 - Type androidx.lifecycle.DispatchQueue is defined multiple times

### ISSUE THREAD

**Issue by mateusz-waldman** [xamarin/GooglePlayServicesComponents#775] opened 2023-05-16 19:17 UTC
Steps to reproduce:
1) Create a new (default) MAUI project (Visual Studio 17.6)
2) Add latest stable Xamarin.Firebase.Analytics

Xamarin.Firebase.Analytics 121.2.0.1 **works**
Xamarin.Firebase.Analytics 121.2.2 **does NOT work**

```
1>MSBUILD : java.exe error JAVA0000: Error in C:\Users\...\.nuget\packages\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/DispatchQueue.class:
1>MSBUILD : java.exe error JAVA0000: Type androidx.lifecycle.DispatchQueue is defined multiple times: C:\Users\...\.nuget\packages\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/DispatchQueue.class, obj\Debug\net7.0-android\lp\154\jl\classes.jar:androidx/lifecycle/DispatchQueue.class
1>MSBUILD : java.exe error JAVA0000: Compilation failed
1>MSBUILD : java.exe error JAVA0000: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\...\.nuget\packages\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar
1>MSBUILD : java.exe error JAVA0000: androidx/lifecycle/DispatchQueue.class
```

Installed Workload Id      Manifest Version       Installation Source
maui-windows               7.0.86/7.0.100         VS 17.6.33712.159
maui-maccatalyst           7.0.86/7.0.100         VS 17.6.33712.159
maui-ios                   7.0.86/7.0.100         VS 17.6.33712.159
maui-android               7.0.86/7.0.100         VS 17.6.33712.159
android                    33.0.46/7.0.100        VS 17.6.33712.159
maccatalyst                16.4.7054/7.0.100      VS 17.6.33712.159
ios                        16.4.7054/7.0.100      VS 17.6.33712.159

**Comment by AlexNik4** [comment] 2023-05-18 03:33
I am getting the same error with new .NET 7 Android project that has:

    <PackageReference Include="ReactiveUI.AndroidX" Version="18.4.44" />
    <PackageReference Include="Xamarin.GooglePlayServices.Code.Scanner" Version="116.0.0" />

Simple repro project here: https://github.com/AlexNik4/barcode-scan-java0000

**Comment by moljac** [comment] 2023-05-24 09:55
Duplicate

https://github.com/xamarin/AndroidX/issues/717

**Comment by jonpryor** [comment] 2023-05-25 23:56
[Possible workaround](https://discord.com/channels/732297728826277939/732297837953679412/1111390450515972157)?

> you'll have to manually add the newest Lifecycle nugets, since nuget always chooses the lowest transitive dependency that it can

**Comment by TheSundayDev** [comment] 2023-05-26 10:40
same issue, can you tell me wht to do in order to solve? 
thanks

Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVA0000	Error in D:\nuget\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/DispatchQueue.class:
Type androidx.lifecycle.DispatchQueue is defined multiple times: D:\nuget\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/DispatchQueue.class, obj\Debug\net7.0-android33.0\lp\176\jl\classes.jar:androidx/lifecycle/DispatchQueue.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: D:\nuget\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar
androidx/lifecycle/DispatchQueue.class
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
	at com.android.tools.r8.D8.main(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: D:\nuget\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/DispatchQueue.class
	at Version.fakeStackEntry(Version_3.3.75.java:0)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:75)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:27)
	at com.android.tools.r8.internal.Fj.b(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:2)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:17)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:85)
	... 1 more
Caused by: com.android.tools.r8.internal.f: Type androidx.lifecycle.DispatchQueue is defined multiple times: D:\nuget\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/DispatchQueue.class, obj\Debug\net7.0-android33.0\lp\176\jl\classes.jar:androidx/lifecycle/DispatchQueue.class
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:14)
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:33)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:6)
	at com.android.tools.r8.graph.B2$a.e(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:110)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:25)
	at com.android.tools.r8.D8.d(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:606)
	at com.android.tools.r8.D8.c(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:1)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:24)
	... 5 more
Directory 'obj\Debug\net7.0-android33.0\lp\176' is from 'androidx.lifecycle.lifecycle-runtime-ktx.aar'.

**Comment by AlexNik4** [comment] 2023-05-26 19:49
@jonpryor I tried adding the Xamarin.AndroidX.Lifecycle.Common package manually. None of the versions worked:
Using Xamarin.AndroidX.Lifecycle.Common 2.6.1 or lower:
`Error	NU1605	Warning As Error: Detected package downgrade: Xamarin.AndroidX.Lifecycle.Common from 2.6.1.1 to 2.6.1.`

Using 2.6.1.1 I get the same error as without the manual reference:
`Error	JAVA0000	Error in C:\Users\Alex\.nuget\packages\xamarin.androidx.lifecycle.common\2.6.1.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/DispatchQueue.class:`

Using 2.6.1.2 (latest version):
`Error	JAVA0000	Error in C:\Users\Alex\.nuget\packages\xamarin.androidx.lifecycle.common\2.6.1.2\buildTransitive\net6.0-android31.0\..\..\jar\androidx.lifecycle.lifecycle-common.jar:androidx/lifecycle/LifecycleController.class:`

Nothing in the full error references any other lifecycle packages.

**Comment by moljac** [comment] 2023-06-01 16:01
As temp workaround try explicitly adding following PackageReferences:

```
		<PackageReference Include="Xamarin.AndroidX.Activity" Version="1.7.2" />
		<PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.7.2" />
```

and yes - please report here if workaround works.

**Comment by AlexNik4** [comment] 2023-06-01 17:37
Yes! That worked. In fact adding just:
`<PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.7.2" />`
to was enough to build and use the new code scan package.

But there are exactly 100 JAVAC warnings as well. Hope these can be cleaned up in the future:
![image](https://github.com/xamarin/GooglePlayServicesComponents/assets/53029348/a6a6f38c-b0d8-4aba-8124-a0cb93dafb42)

**Comment by IgorSava** [comment] 2023-06-02 13:33
> As temp workaround try explicitly adding following PackageReferences:
> 
> ```
> 		<PackageReference Include="Xamarin.AndroidX.Activity" Version="1.7.2" />
> 		<PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.7.2" />
> ```
> 
> and yes - please report here if workaround works.

it`s works !

**Comment by moljac** [comment] 2023-06-08 17:29
> But there are exactly 100 JAVAC warnings as well. Hope these can be cleaned up in the future

This was fixed. Google moves code around and that was the reason for those warnings. Try using `Xamarin.AndroidX.Annotation:1.6.0.3`. That should help

**Comment by moljac** [comment] 2023-06-08 17:29
Closing this issue

**Closed by moljac** 2023-06-08 17:29 UTC

**Comment by moljac** [comment] 2023-06-19 18:09
> @moljac thank you for the workarounds.

You are welcome.

> Could you please provide additional information what to expect next?
> 
> 1. issue was closed and the final solution (not a workaround) is to always reference Xamarin.AndroidX.Activity.Ktx whenever someone wants to use Xamarin.Firebase.Analytics

In general, no. We took some measures that will render that as unnecessary. The problem is that google moves types from artifact to artifact and if your real world app setup (nuget dependencies) cause that transitive dependencies reference 2 nugets/assemblies where some type appear, this error might happen. Especially with 3rd party libraries/packages/plugins which reference older packages and that is not within our control.
 
> 2. issue was closed because of the temporary workaround is available - how would the proper fix be communicated (when explicitly referencing Xamarin.AndroidX.Activity.Ktx will no longer be required)

Simply: update to latest and be vocal that 3rd party libraries are updated.

In the future I will do "alignment bumps" to ensure that published packages use always the latest, but that is for 500+ packages we maintain. If someone uses older version this error might happen again.

Another reason I closed this issue - it is easier to detect if the issue is with our nuget or some 3rd party.

Just this issue:

```
<PackageReference Include="ReactiveUI.AndroidX" Version="18.4.44" />
<PackageReference Include="Xamarin.GooglePlayServices.Code.Scanner" Version="116.0.0" />
```

GPS-FB-MLKit was aligned week or so ago.

OP's dependecy:
```
Xamarin.Firebase.Analytics
```

because it was prior to "alignment bump"
