### ISSUE TITLE
v71-preview-1: Firebase Perf NullPointerException

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/GooglePlayServicesComponents#191] opened 2019-03-23 17:00 UTC
### Describe your Issue:
After upgrading to the new v71 preview, I get a `NullPointerException`, somewhere between Firebase Perf and Firebase InstanceID

`[FA] Task exception on worker thread: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference: com.google.android.gms.internal.measurement.zzfb.zzgj(Unknown Source:29)`

This happens before any explicit code to do with Firebase has run (apparently in the activity onResume).

### Steps to Reproduce

Create an Xamarin Android app, add `Xamarin.Firebase.Perf` 71 and add a `google-services.json` with Firebase Analytics setup.

### Include any relevant Exception Stack traces, build logs, adb logs:

```
[FirebasePerformance] onResume md57ffafda0774e6b18671b6b2d6fccaf8e.MainActivity:4180807
[AndroidRuntime] FATAL EXCEPTION: pool-2-thread-2
[AndroidRuntime] Process: net.gameswithgravitas.tictactoe, PID: 19078
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.gms.internal.firebase-perf.zzq.zzb(boolean)' on a null object reference
[AndroidRuntime] 	at com.google.android.gms.internal.firebase-perf.zzg.zzc(Unknown Source:2)
[AndroidRuntime] 	at com.google.android.gms.internal.firebase-perf.zzk.run(Unknown Source:4)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[AndroidRuntime] 	at java.lang.Thread.run(Thread.java:764)
[AndroidRuntime] FATAL EXCEPTION: pool-2-thread-1
[AndroidRuntime] Process: net.gameswithgravitas.tictactoe, PID: 19078
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.getId()' on a null object reference
[AndroidRuntime] 	at com.google.android.gms.internal.firebase-perf.zzg.zzq(Unknown Source:12)
[AndroidRuntime] 	at com.google.android.gms.internal.firebase-perf.zzg.zzp(Unknown Source:47)
[AndroidRuntime] 	at com.google.android.gms.internal.firebase-perf.zzg.zzb(Unknown Source:0)
[AndroidRuntime] 	at com.google.android.gms.internal.firebase-perf.zzh.run(Unknown Source:2)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
[AndroidRuntime] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
[AndroidRuntime] 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by nlapham** [comment] 2019-03-26 19:49
I'm getting the same issue while trying to integrate Xamarin.Firebase.Perf into a Xamarin forms android project

**Comment by GalaxiaGuy** [comment] 2019-03-27 13:24
Considering #192, it may not be Firebase Perf that has the problem, just Firebase Instance ID.

**Comment by Redth** [comment] 2019-04-01 16:59
It looks like sometimes a full clean and rebuild is required after adding the google-services.json file and setting it as a `GoogleServicesJson` build action.  Please try this and try again, I can't reproduce this error locally, it's working correctly for me when everything is properly setup.

**Comment by Redth** [comment] 2019-04-01 17:00
This also appears to be a duplicate of #192 which is the root of the problem (still should be fixed in the same way).  Closing, please track any more progress in #192.

**Closed by Redth** 2019-04-01 17:00 UTC
Labels: needs-info
